//задания на уровень
let taskName = "quiz04";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			sizeTask: `9rem`,
			sizeFormatAnswer:"9rem",
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
			answer:"Кто сильнее вас",
			},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/02.jpg",
			// audio:"./music/02.mp3",
//			secAnswer:,
			answer:"Завтра",
			}
			,
 	task3 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/03.jpg",
			// audio:"./music/03.mp3",
//			secAnswer:,
			answer:"Мудр",
			},
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/04.jpg",
			// audio:"./music/04.mp3",
//			secAnswer:,
			answer:"Без удовольствия",
			},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/05.jpg",
				// audio:"./music/05.mp3",
//			secAnswer:,
			answer:"Памятных шрамов",
			}
]			