//задания на уровень
let taskName = "quiz05";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.png",
			// audio:"./images/01.mp3",
			secAnswer:10,
			formatAnswer:"Два слова на русском языке",
			answer:"Вынос мозга",
			},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/02.png",
			// audio:"./music/02.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Картошка в мундире",
			}
			,
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/04.png",
			// audio:"./music/04.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Солнце глаза режет",
			},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/05.png",
				// audio:"./music/05.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Сопротивление бесполезно"
			},
 	task6 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/06.png",
				// audio:"./music/06.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Яблоки на снегу",
			}
]			